version: "3.8"

services:
  frontend:
    image: jhonmayta/frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: jhonmayta/backend:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
